version: "3.9"
services:
  ssh-tunnel:
      image: ssh-tunnel
      build:
        context: ./
        dockerfile: ./ssh-tunnel/Dockerfile
      volumes:
        - ".ssh:/opt/ssh_tunnel/.ssh:ro"
      networks:
        - localnetwork
  rsyslog:
      image: rsyslog
      build:
        context: ./
        dockerfile: ./rsyslog/Dockerfile
      volumes:
        - "./log:/var/log/remote"
      ports:
        - 514:514
      networks:
        - localnetwork
networks:
  localnetwork:
