version: "3.9"
services:
  ssh-tunnel:
      image: dsp8ef9/syslog_ssh:latest
      build:
        context: ./
        dockerfile: ./ssh-tunnel/Dockerfile
      volumes:
        - "./ssh:/opt/ssh_tunnel/.ssh:ro"
        - "./secret:/opt/ssh_tunnel/.secret:ro"
      networks:
        - localnetwork
  rsyslog:
      image: dsp8ef9/syslog_rsyslog:latest
      build:
        context: ./
        dockerfile: ./rsyslog/Dockerfile
      volumes:
        - "./log:/var/log/remote"
      networks:
        - localnetwork
networks:
  localnetwork:
