version: "3.9"
services:
  rsyslog:
      image: rsyslog
      build:
        context: ./
        dockerfile: Dockerfile
      volumes: 
        - "./log:/var/log/remote"
      ports: 
        - 514:514
