name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_syslog_rsyslog:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: rsyslog/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/syslog_rsyslog:latest

  build_syslog_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ssh-tunnel/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/syslog_ssh:latest